### ISSUE TITLE
Not implemented types

### ISSUE THREAD

**Issue by bahchis** [SponsorPay/ruby-binlog#4]
I have tried using https://github.com/izumiya/fluent-plugin-mysql-binlog, which uses ruby-binlog to process binlog events.

According to the documentation here, the following datatypes are not supported:
ENUM
SET
GEOMETRY

I am getting the value "not implemented" instead of the field value on mediumint and date types (probably more types, but those I saw).
What could be the issue?

Thank you.

**Comment by carlosmoutinho** [comment]
Hi,

Just to clarify, the ruby-binlog that you get when you use the fluent-plugin-mysql-binlog is not the one in this repo; it's this one: https://bitbucket.org/winebarrel/ruby-binlog

In any case, ruby-binlog depends on [mysql-replication-listener](https://bitbucket.org/winebarrel/mysql-replication-listener) which might not support the new mysql types introduced in mysql 5.6.

If that turns out to be the case then I would suggest you have a look our fork of [sponsorpay/mysql-replication-listener](https://github.com/SponsorPay/mysql-replication-listener/commits/master) where we try to add support for some types.

Hope this helps!

**Comment by bahchis** [comment]
Hi @carlosmoutinho ,
Thanks for the quick reply.

It is indeed installing the gem which is the bitbucket ruby-binlog using gem, but we install the mysql-replication-listener from the repo you have mentioned, since none is installed automatically.

Should that be enough to get the datatypes support (mysql 5.1 btw)? Could you please give some directions of what is the correct installation to get this support?

Thanks
